language: java
env:
  - TEST_DIR=yajco-example-deskNielsen
  - TEST_DIR=yajco-example-extMathExpressions
  - TEST_DIR=yajco-example-imperativeLang
  - TEST_DIR=yajco-example-json
  - TEST_DIR=yajco-example-mathExpressions
  - TEST_DIR=yajco-example-robotKarel
  - TEST_DIR=yajco-example-simpleRobot
  - TEST_DIR=yajco-example-stateMachine
script:
  - git clone https://github.com/kpi-tuke/yajco-examples && cd yajco-examples
  - cd $TEST_DIR && mvn verify -Dyajco.version="0.5.9" && mvn clean
  - cd ..
  - cd rm -rf yajco-examples