language: java
env:
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-deskNielsen
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-extMathExpressions
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-gettingStarted
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-imperativeLang
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-json
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-mathExpressions
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-robotKarel
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-simpleRobot
  - EXAMPLE_TEST_DIR=yajco-examples/yajco-example-stateMachine
script:
  - mvn install
  - git clone https://github.com/mfecenko/yajco-examples
  - YAJCO_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version | grep -v '\[')
  - cd $EXAMPLE_TEST_DIR && mvn verify -Dyajco.version=$YAJCO_VERSION && mvn clean
  - rm -rf yajco-examples